# config
logo: /images/avatar.png
keywords: "laurence stant, developer, engineer, electronics, physics, microwave, radio"
pubkey:
menu:
  Home: /
  Articles: /articles
  About: /about
  Tools: /tools

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics:
